### ISSUE TITLE
Unable to install @0.7.9, encounter errors for 'gulp es5' in post-install script

### ISSUE THREAD

**Issue by youngtt** [liangzeng/cqrs#1]
9724 info install cqrs@0.7.9
9725 info postinstall cqrs@0.7.9
9726 verbose unsafe-perm in lifecycle false
9727 info cqrs@0.7.9 Failed to exec postinstall script
9728 verbose unlock done using /Users/young/.npm/_locks/cqrs-291d4efa73812880.lock for /Users/young/Dev/X/3.2/event-store/node_modules/cqrs
9729 verbose stack Error: cqrs@0.7.9 postinstall: `gulp es5`
9729 verbose stack Exit status 127
9729 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9729 verbose stack     at EventEmitter.emit (events.js:110:17)
9729 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9729 verbose stack     at ChildProcess.emit (events.js:110:17)
9729 verbose stack     at maybeClose (child_process.js:1015:16)
9729 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
9730 verbose pkgid cqrs@0.7.9
9731 verbose cwd /Users/young/Dev/X/3.2/event-store
9732 error Darwin 14.3.0
9733 error argv "node" "/usr/local/bin/npm" "install" "cqrs" "--save"
9734 error node v0.12.2
9735 error npm  v2.7.4
9736 error code ELIFECYCLE
9737 error cqrs@0.7.9 postinstall: `gulp es5`
9737 error Exit status 127
9738 error Failed at the cqrs@0.7.9 postinstall script 'gulp es5'.
9738 error This is most likely a problem with the cqrs package,
9738 error not with npm itself.
9738 error Tell the author that this fails on your system:
9738 error     gulp es5
9738 error You can get their info via:
9738 error     npm owner ls cqrs
9738 error There is likely additional logging output above.
9739 verbose exit [ 1, true ]
9740 verbose unbuild node_modules/cqrs
9741 info preuninstall cqrs@0.7.9
9742 info uninstall cqrs@0.7.9
9743 verbose unbuild rmStuff cqrs@0.7.9 from /Users/young/Dev/X/3.2/event-store/node_modules
9744 info postuninstall cqrs@0.7.9
9745 silly gentlyRm /Users/young/Dev/X/3.2/event-store/node_modules/cqrs is being purged from base /Users/young/Dev/X/3.2/event-store
9746 verbose gentlyRm don't care about contents; nuking /Users/young/Dev/X/3.2/event-store/node_modules/cqrs
9747 silly vacuum-fs purging /Users/young/Dev/X/3.2/event-store/node_modules/cqrs
9748 silly vacuum-fs quitting because other entries in /Users/young/Dev/X/3.2/event-store/node_modules

**Comment by liangzeng** [comment]
@youngtt  fixed at v0.8.5, thanks.
