### ISSUE TITLE
CQRS with EF6 Code First

### ISSUE THREAD

**Issue by vizetar** [liangzeng/cqrs#10]
Folks,

I am creating CQRS architecture for my web api. Is it possible to set up CQRS with EF6 code first approach? If Yes, then our cqrs domains will work as my entities for code first , Or we have to create separate entities for this? 

Thanks

**Comment by liangzeng** [comment]
welcome,  my english is a little , so write code answer .

step one: create Actor sub class

```
class User extends Actor { ... }
class Transfer extends Actor {... }
```


step two:    register Actor class into domain.
```
const Domain = require("cqrs");

const domain = new Domain();

// register User Actor into the domain object.
domain.register(User).register(Transfer);

```
