### ISSUE TITLE
duplicated calls of event dispatcher init() ?

### ISSUE THREAD

**Issue by youngtt** [liangzeng/cqrs#4]
```javascript
var Domain = require('cqrs').Domain;
var domain = new Domain();
```

debug output:
```
  eventstore init event dispatcher +0ms
  eventstore:eventdispatcher undefined +3ms
  eventstore init event dispatcher +1ms
  eventstore:eventdispatcher undefined +1ms
```

**Comment by liangzeng** [comment]
@youngtt  when new domain, then call once `init()` 

https://github.com/liangzeng/cqrs/blob/master/src/lib/Domain.js#L57

**Comment by youngtt** [comment]
Would another call here be an issue?
https://github.com/liangzeng/cqrs/blob/master/src/lib/EventBus.js#L17

**Comment by liangzeng** [comment]
@youngtt thanks  , look  https://github.com/liangzeng/cqrs/tree/0.9.0
