### ISSUE TITLE
Error running example (main.js) when using mongodb as es store

### ISSUE THREAD

**Issue by youngtt** [liangzeng/cqrs#5]
In main.js, changing [new Domain()](https://github.com/liangzeng/cqrs/blob/master/src/example/main.js#L5) to:
```javascript
var domain = new Domain({ type: 'mongodb', host: '127.0.0.1' });
```
generated these errors:
```
    this.snapshots.findOne(findStatement, { sort: [['revision', 'desc'], ['ver
                  ^
TypeError: Cannot read property 'findOne' of undefined
    at Mongo._.extend.getSnapshot (/Users/young/Dev/X/3.2/service-eventstore/node_modules/eventstore/lib/databases/mongodb.js:354:19)
    at getSnapshot (/Users/young/Dev/X/3.2/service-eventstore/node_modules/eventstore/lib/eventstore.js:240:20)
    at fn (/Users/young/Dev/X/3.2/service-eventstore/node_modules/eventstore/node_modules/async/lib/async.js:641:34)
    at Immediate._onImmediate (/Users/young/Dev/X/3.2/service-eventstore/node_modules/eventstore/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

Using mongodb v3.0.2

**Comment by liangzeng** [comment]
@youngtt  look   https://github.com/adrai/node-eventstore#provide-implementation-for-storage

**Comment by liangzeng** [comment]
@youngtt   use    https://github.com/liangzeng/cqrs/tree/0.9.2

**Comment by youngtt** [comment]
Thanks. Tried using v0.9.2, same error.

Could it be that the eventstore is not fully ready/connected when cqrs attempt to access es?

**Comment by liangzeng** [comment]
@youngtt  please first run mongodb.

**Comment by youngtt** [comment]
yes, mongodb was already running.
I meant that, in test.js,
* the error is caused by call to ```domain.create()```
* could it be that when we call ```domain.create()```, ```new Domain()``` has not completed and **event store's mongo connection** is still not ready?
```javascript
...
var domain = new Domain({ type: 'mongodb', host: '127.0.0.1' });
...
...
domain.create("User", {}, function (err, userId) {
   ...
});
```
Do we need a callback for ```new Domain()```?

**Comment by liangzeng** [comment]
@youngtt  yes!   need a  `init` event , then mean inited.

**Comment by youngtt** [comment]
Yes, that would do too :)

**Comment by liangzeng** [comment]
@youngtt   https://github.com/liangzeng/cqrs/tree/0.9.3
```js
const domain = new Domain(options);
domain.on('init',()=>{
     domain.create('User',{name:'leo'});
     ... ...
});
```

**Comment by youngtt** [comment]
Working now.  Thanks!
