### ISSUE TITLE
Examples for sub-classing Actor in ES5

### ISSUE THREAD

**Issue by youngtt** [liangzeng/cqrs#6]
We need to integrate this module into our existing ES5 codebase and are not familiar with ES6 or ES5/6 mix-use.

Do you have examples on how to sub-class ```Actor``` and ```AbstractActor``` in ES5?

Great if you could also provide guidance/references on this.

Thanks :)

**Comment by liangzeng** [comment]
@youngtt  look https://github.com/liangzeng/cqrs/tree/0.9.4#step-2--create-a-actor-class
please use version 0.9.4    :)

**Comment by youngtt** [comment]
It works!  Appreciate the super fast response :+1:
