### ISSUE TITLE
Command/query handlers

### ISSUE THREAD

**Issue by nripendra** [liangzeng/cqrs#9]
In my mind cqrs would also involve command/query handlers, and a way to transfer command/query to respective handlers. Doesn't seem like this framework has an implementation for such? Could you please point me in right direction how can it be implemented?

Thanks in advance.

**Comment by liangzeng** [comment]
sorry, my english is a little. so ... haha

CQS is write , R is readonly DB .  It's just thinking, don't be trapped.

```
const domain = new Domain();  // domain is CQS

// listen  update event.  can extended function.
domain.on(update_event_name,handle) ; 

// listen  update event.
domain.on(update_event_name,function(event){
      // update readonly database.
      readDB.update( ... );
}) ; 

//  update actor.name , and write event to eventstore. 
domain.call('User.id001.changeName',{name:'leo'}) 

//  Q - query use readDB.
readDB.find(...) 

```

**Comment by nripendra** [comment]
@liangzeng 

Thanks for your answer.
